name: Auto I18N

env:
  API_KEY: ${{ secrets.TRANSLATE_API_KEY}}
  MODEL: ${{ vars.MODEL || 'deepseek/deepseek-v3.1'}}
  BASE_URL: ${{ vars.BASE_URL || 'https://api.ppinfra.com/openai'}}

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  auto-i18n:
    runs-on: ubuntu-latest
    name: Auto I18N

    steps:
      - name: ğŸˆâ€â¬› Checkout
        uses: actions/checkout@v5

      - name: ğŸ“¦ Setting Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: ğŸ“¦ Dependencies
        run: npm install openai cli-progress tsx

      - name: ğŸƒâ€â™€ï¸ Translate
        run: tsx scripts/update-i18n.ts

      - name: ğŸš€ Push changes
        uses: ad-m/git-push@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
